Update utils.py
rugglcon/python-backgroundchanger pull request #25
Opened 2020-10-13 19:15 UTC by CodeLongAndProsper90

This adds support for `Feh` and `Nitrogen`, if Ubuntu or Elementary is not found.
This has no effect on existing options, and only comes into play if gsettings is not found.

2020-10-13 20:15 UTC, rugglcon requested changes
Please address the comments I left

2020-10-13 20:15 UTC, rugglcon commented on backgroundchanger/utils.py
> +                'access_key': data['access_key'],
Please remove these spacing changes

2020-10-13 20:15 UTC, rugglcon commented on backgroundchanger/utils.py
> +            'height': root.winfo_vrootheight(),
Please remove these spacing changes

2020-10-13 20:15 UTC, rugglcon commented on backgroundchanger/utils.py
> +                    ]
please revert the spacing on this return statement

2020-10-13 20:15 UTC, rugglcon commented on backgroundchanger/utils.py
> +                    phot o_name))
fix variable name
```suggestion
                    photo_name))
```

2020-10-13 20:15 UTC, rugglcon commented on backgroundchanger/utils.py
> +            '{} is not ye t implemented to change the background. However, you can still change the background. photo name: {}'.format(
fix word typo
```suggestion
            '{} is not yet implemented to change the background. However, you can still change the background. photo name: {}'.format(
```

2020-10-13 20:15 UTC, rugglcon commented on README.md
> +This optionally requres `feh` or `nitrogen` if you are not using Ubuntu or Rlementary OS.
typo
```suggestion
This optionally requres `feh` or `nitrogen` if you are not using Ubuntu or Elementary OS.
```

2020-10-13 21:54 UTC, CodeLongAndProsper90 commented
Ah yes, sorry about those changes, my IDE was a little overzealous.

2020-10-14 02:45 UTC, rugglcon requested changes
Still some spacing changes it looks like, on the return statements

2020-10-14 13:17 UTC, CodeLongAndProsper90 commented
I think I'll close this one and open a new pr, using a different ide. Or just fix Vim.

2020-10-14 13:17 UTC, closed without merging